Organic/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('frontend.urls'))
]

frontend/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start_page, name='start'),
    url(r'^(?P<class_text_id>\w+)/$', views.class_page, name='class')
]

classes/models.py
from django.db import models


class OrganicClass(models.Model):
    text_id = models.CharField(max_length=32, blank=True, null=True, default=None)
    name = models.CharField(max_length=64)
    formula = models.CharField(max_length=16)
    properties = models.TextField()

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Класс'
        verbose_name_plural = 'Классы'

frontend/models.py
from django.db import models

reactions/models.py
from django.db import models
from classes.models import OrganicClass


def transform(inp):
    res = ''
    num = ''
    for i in range(0, len(inp)):
        if (inp[i].isdigit()) and (inp[i-1].isalpha() or num):
            num += inp[i]
            if i == len(inp)-1:
                res += '<sub>' + num + '</sub>'
        elif num:
            res += '<sub>' + num + '</sub>'
            res += inp[i]
            num = ''
        else:
            res += inp[i]
            num = ''
    return res


class Reaction(models.Model):
    organic_class = models.ForeignKey(OrganicClass)
    name = models.CharField(max_length=128)
    materials = models.CharField(max_length=256)
    products = models.CharField(max_length=256)
    conditions = models.CharField(max_length=128, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    picture = models.ImageField(upload_to='reactions', blank=True, null=True)
    is_active = models.BooleanField(default=True)

    materials_trans = models.CharField(max_length=256, blank=True, null=True, default=None)
    products_trans = models.CharField(max_length=256, blank=True, null=True, default=None)

    def __str__(self):
        return "%s %s" % (self.organic_class.name, self.name.lower())

    class Meta:
        verbose_name = 'Реакция'
        verbose_name_plural = 'Реакции'

    def save(self, *args, **kwargs):
        self.materials_trans = transform(self.materials)
        self.products_trans = transform(self.products)

        super(Reaction, self).save(*args, **kwargs)


class ReceivingReaction(models.Model):
    organic_class = models.ForeignKey(OrganicClass)
    name = models.CharField(max_length=128)
    materials = models.CharField(max_length=256)
    products = models.CharField(max_length=256)
    conditions = models.CharField(max_length=128, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    picture = models.ImageField(upload_to='reactions', blank=True, null=True)
    is_active = models.BooleanField(default=True)

    materials_trans = models.CharField(max_length=256, blank=True, null=True, default=None)
    products_trans = models.CharField(max_length=256, blank=True, null=True, default=None)

    def __str__(self):
        return "%s | %s" % (self.organic_class.name, self.name.lower())

    class Meta:
        verbose_name = 'Реакция получения'
        verbose_name_plural = 'Реакции получения'

    def save(self, *args, **kwargs):
        self.materials_trans = transform(self.materials)
        self.products_trans = transform(self.products)

        super(ReceivingReaction, self).save(*args, **kwargs)

classes/views.py
from django.shortcuts import render

# Create your views here.

frontend/views.py
from django.shortcuts import render
from classes.models import OrganicClass


def start_page(request):
    organic_classes = OrganicClass.objects.all()
    return render(request, 'start_page.html', locals())


def class_page(request, class_text_id):
    organic_classes = OrganicClass.objects.all()
    organic_class = OrganicClass.objects.get(text_id=class_text_id)
    return render(request, 'organic_class_page.html', locals())

reactions/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Органика</title>

        <!-- CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'style.css' %}">

    </head>

    <body>
        <div class="wrapper">
            <div class="wrapper-content">
                {% include 'navmenu.html' %}
                <div class="container main-container">
                    <div class="row">
                        <div class="col-md-12">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <script src="http://getbootstrap.com/assets/js/vendor/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="http://www.jasny.net/bootstrap/dist/js/jasny-bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</html>

templates/navmenu.html
<nav class="navmenu navmenu-default navmenu-fixed-left navmenu-inverse" role="navigation">
    <a class="navmenu-brand" href="#">Органическая химия</a>

    <ul class="nav navmenu-nav">
        {% for organic_class in organic_classes %}
            <li class="navmenu-element"><a href="{% url 'class' organic_class.text_id %}">{{ organic_class.name }}</a></li>
        {% endfor %}
    </ul>
</nav>

templates/organic_class_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h2>{{ organic_class.name }}</h2>
    <div class="panel-group" id="collapse-group">
         <div class="panel panel-default">
             <button type="button" class="btn btn-warning" data-toggle="collapse"
                     data-parent="#collapse-group" href="#el_1">
                 Физические свойства
             </button>
             <div id="el_1" class="panel-collapse collapse in">
                 <div class="panel-body">
                     {% autoescape off %}
                        {{ organic_class.properties }}
                     {% endautoescape %}
                 </div>
             </div>
         </div>
         <div class="panel panel-default">
             <button type="button" class="btn btn-primary" data-toggle="collapse"
                     data-parent="#collapse-group" href="#el_2">
                 Химические свойства
             </button>
             <div id="el_2" class="panel-collapse collapse">
                 <div class="panel-body">
                     <ul>
                         {% autoescape off %}
                             {% for reaction in organic_class.reaction_set.all %}
                                 <li>
                                     <p class="font-weight-bold">{{ reaction.name }}</p>
                                     <div class="well">
                                         {{ reaction.materials_trans }}
                                         <span class="glyphicon glyphicon-arrow-right"></span>
                                         {{ reaction.products_trans }}
                                         {% if reaction.conditions %}
                                             ({{ reaction.conditions }})
                                         {% endif %}
                                         {% if reaction.picture %}
                                             <br>
                                             <img src="../{{ reaction.picture.url }}" class="img-responsive">
                                         {% endif %}
                                     </div>
                                     {% if reaction.description %}
                                        <p class="un-bold">{{ reaction.description }}</p>
                                     {% endif %}
                                 </li>
                             {% endfor %}
                         {% endautoescape %}
                     </ul>
                 </div>
             </div>
         </div>
         <div class="panel panel-default">
             <button type="button" class="btn btn-info" data-toggle="collapse"
                     data-parent="#collapse-group" href="#el_3">
                 Получение
             </button>
             <div id="el_3" class="panel-collapse collapse">
                 <div class="panel-body">
                     <ul>
                         {% autoescape off %}
                             {% for receivingreaction in organic_class.receivingreaction_set.all %}
                                 <li>
                                     <p class="font-weight-bold">{{ receivingreaction.name }}</p>
                                     <div class="well">
                                         {{ receivingreaction.materials_trans }}
                                         <span class="glyphicon glyphicon-arrow-right"></span>
                                         {{ receivingreaction.products_trans }}
                                         {% if receivingreaction.conditions %}
                                            ({{ receivingreaction.conditions }})
                                         {% endif %}
                                         {% if reaction.picture %}
                                             <br>
                                             <img src="{{ reaction.picture.url }}" class="img-responsive">
                                         {% endif %}
                                     </div>
                                     {% if receivingreaction.description %}
                                         <p class="un-bold">{{ receivingreaction.description }}</p>
                                     {% endif %}
                                 </li>
                             {% endfor %}
                         {% endautoescape %}
                     </ul>
                 </div>
             </div>
         </div>
    </div>
{% endblock %}

templates/start_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    Choose class
{% endblock %}